version: "3.9"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    
  wordpress:
    depends_on:
      - db
    build: .
    volumes:
      - wordpress_data:/var/www/html
      #- ./dist:/var/www/html/wp-content/plugins/sesamy
      - ./src:/var/www/html/wp-content/plugins/sesamy
      - ./demo/themes/twentytwentytwo-child:/var/www/html/wp-content/themes/twentytwentytwo-child
      - ./wordpress.ini:/usr/local/etc/php/conf.d/wordpress.ini
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1     
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG:
          client_host=host.docker.internal
          start_with_request=yes
volumes:
  db_data: {}
  wordpress_data: {}