version: "3.9"
name: sesamy
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports: 
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    build: .
    volumes:
      - wordpress_data:/var/www/html
      - ./src:/var/www/html/wp-content/plugins/sesamy
      - ./demo/themes/twentytwentytwo-child:/var/www/html/wp-content/themes/twentytwentytwo-child
      - ./wordpress.ini:/usr/local/etc/php/conf.d/wordpress.ini
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: client_host=host.docker.internal start_with_request=yes
  
  test:
    depends_on:
      - db
    image: sesamy/wp-test
    build: 
      context: .
      dockerfile: ./test/Dockerfile
    volumes:
      - ./src:/wordpress/wp-content/plugins/sesamy/
      - ./test/entrypoint.sh:/usr/local/bin/entrypoint.sh
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_USER: root
        WORDPRESS_DB_PASSWORD: root
        WORDPRESS_DB_NAME: sesamy_test
        WORDPRESS_TEST_VERSION: latest
    profiles:
      - test
  wpcli:
      depends_on:
        - wordpress
      image: wordpress:cli
      command: tail -f /dev/null
      volumes:
        - wordpress_data:/var/www/html
      environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_USER: wordpress
        WORDPRESS_DB_PASSWORD: wordpress
        WORDPRESS_DB_NAME: wordpress
        WORDPRESS_TEST_VERSION: latest
      profiles:
        - dev
volumes:
  db_data: {}
  wordpress_data: {}
